import {
  URL_SLUG_GROUPS,
  URL_SLUG_RAFFLE,
  URL_SLUG_NUMBER,
  URL_SLUG_FACEBOOK,
  URL_SLUG_ARROW,
  URL_SLUG_COIN,
  URL_SLUG_LETTER,
} from './urlSlugs';

export const ANALYTICS_TYPE_GROUPS = 'Groups';
export const ANALYTICS_TYPE_RAFFLE = 'Raffle';
export const ANALYTICS_TYPE_NUMBER = 'Number';
export const ANALYTICS_TYPE_FACEBOOK = 'FacebookRaffle';
export const ANALYTICS_TYPE_ARROW = 'Spin Arrow';
export const ANALYTICS_TYPE_COIN = 'Coin';
export const ANALYTICS_TYPE_LETTER = 'Letter';

export const analyticsTypesBySlug = {
  [URL_SLUG_GROUPS]: ANALYTICS_TYPE_GROUPS,
  [URL_SLUG_NUMBER]: ANALYTICS_TYPE_NUMBER,
  [URL_SLUG_RAFFLE]: ANALYTICS_TYPE_RAFFLE,
  [URL_SLUG_FACEBOOK]: ANALYTICS_TYPE_FACEBOOK,
  [URL_SLUG_ARROW]: ANALYTICS_TYPE_ARROW,
  [URL_SLUG_COIN]: ANALYTICS_TYPE_COIN,
  [URL_SLUG_LETTER]: ANALYTICS_TYPE_LETTER,
};
