const TYPE_NODE_ENV_PRODUCTION = 'production';

const TYPE_APP_ENV_PRODUCTION = 'production';
const TYPE_APP_ENV_STAGING = 'staging';
const TYPE_APP_ENV_LOCAL = 'local';
const TYPE_APP_ENV_TEST = 'test';

const APP_ENV_TYPES = [
  TYPE_APP_ENV_PRODUCTION,
  TYPE_APP_ENV_STAGING,
  TYPE_APP_ENV_LOCAL,
  TYPE_APP_ENV_TEST,
];

module.exports = {
  TYPE_NODE_ENV_PRODUCTION,
  TYPE_APP_ENV_PRODUCTION,
  TYPE_APP_ENV_STAGING,
  TYPE_APP_ENV_LOCAL,
  TYPE_APP_ENV_TEST,
  APP_ENV_TYPES,
};
