/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The DrawMetadata model module.
* @module model/DrawMetadata
* @version v1
*/
export default class DrawMetadata {
    /**
    * Constructs a new <code>DrawMetadata</code>.
    * @alias module:model/DrawMetadata
    * @class
    * @param client {String} 
    * @param key {String} 
    * @param value {String} 
    */

    constructor(client, key, value) {
        

        
        

        this['client'] = client;this['key'] = key;this['value'] = value;

        
    }

    /**
    * Constructs a <code>DrawMetadata</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DrawMetadata} obj Optional instance to populate.
    * @return {module:model/DrawMetadata} The populated <code>DrawMetadata</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DrawMetadata();

            
            
            

            if (data.hasOwnProperty('client')) {
                obj['client'] = ApiClient.convertToType(data['client'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} client
    */
    client = undefined;
    /**
    * @member {String} key
    */
    key = undefined;
    /**
    * @member {String} value
    */
    value = undefined;








}


