/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The DrawTossPayload model module.
* @module model/DrawTossPayload
* @version v1
*/
export default class DrawTossPayload {
    /**
    * Constructs a new <code>DrawTossPayload</code>.
    * @alias module:model/DrawTossPayload
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>DrawTossPayload</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DrawTossPayload} obj Optional instance to populate.
    * @return {module:model/DrawTossPayload} The populated <code>DrawTossPayload</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DrawTossPayload();

            
            
            

        }
        return obj;
    }









}


