/**
 * EAS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import RaffleResultValuePrize from './RaffleResultValuePrize';





/**
* The RaffleResultValue model module.
* @module model/RaffleResultValue
* @version v1
*/
export default class RaffleResultValue {
    /**
    * Constructs a new <code>RaffleResultValue</code>.
    * @alias module:model/RaffleResultValue
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>RaffleResultValue</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RaffleResultValue} obj Optional instance to populate.
    * @return {module:model/RaffleResultValue} The populated <code>RaffleResultValue</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RaffleResultValue();

            
            
            

            if (data.hasOwnProperty('prize')) {
                obj['prize'] = RaffleResultValuePrize.constructFromObject(data['prize']);
            }
            if (data.hasOwnProperty('participant')) {
                obj['participant'] = ApiClient.convertToType(data['participant'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/RaffleResultValuePrize} prize
    */
    prize = undefined;
    /**
    * @member {Object} participant
    */
    participant = undefined;








}


