/**
 * EAS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import DrawMetadata from './DrawMetadata';
import Participant from './Participant';
import Prize from './Prize';
import RaffleResult from './RaffleResult';





/**
* The Raffle model module.
* @module model/Raffle
* @version v1
*/
export default class Raffle {
    /**
    * Constructs a new <code>Raffle</code>.
    * @alias module:model/Raffle
    * @class
    * @param prizes {Array.<module:model/Prize>} 
    * @param participants {Array.<module:model/Participant>} 
    */

    constructor(prizes, participants) {
        

        
        

        this['prizes'] = prizes;this['participants'] = participants;

        
    }

    /**
    * Constructs a <code>Raffle</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Raffle} obj Optional instance to populate.
    * @return {module:model/Raffle} The populated <code>Raffle</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Raffle();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [RaffleResult]);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], [DrawMetadata]);
            }
            if (data.hasOwnProperty('private_id')) {
                obj['private_id'] = ApiClient.convertToType(data['private_id'], 'String');
            }
            if (data.hasOwnProperty('prizes')) {
                obj['prizes'] = ApiClient.convertToType(data['prizes'], [Prize]);
            }
            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [Participant]);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {Date} created_at
    */
    created_at = undefined;
    /**
    * @member {Date} updated_at
    */
    updated_at = undefined;
    /**
    * @member {String} title
    */
    title = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Array.<module:model/RaffleResult>} results
    */
    results = undefined;
    /**
    * @member {Array.<module:model/DrawMetadata>} metadata
    */
    metadata = undefined;
    /**
    * @member {String} private_id
    */
    private_id = undefined;
    /**
    * @member {Array.<module:model/Prize>} prizes
    */
    prizes = undefined;
    /**
    * @member {Array.<module:model/Participant>} participants
    */
    participants = undefined;








}


