/**
 * Echalo A Suerte
 * API definition for EAS web services
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mariocj89@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The RandomNumberResult model module.
* @module model/RandomNumberResult
* @version 1.0.0
*/
export default class RandomNumberResult {
    /**
    * Constructs a new <code>RandomNumberResult</code>.
    * @alias module:model/RandomNumberResult
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>RandomNumberResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RandomNumberResult} obj Optional instance to populate.
    * @return {module:model/RandomNumberResult} The populated <code>RandomNumberResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RandomNumberResult();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} created
    */
    created = undefined;
    /**
    * @member {Object} value
    */
    value = undefined;








}


