/**
 * EAS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import DrawMetadata from './DrawMetadata';
import RandomNumberResult from './RandomNumberResult';





/**
* The RandomNumber model module.
* @module model/RandomNumber
* @version v1
*/
export default class RandomNumber {
    /**
    * Constructs a new <code>RandomNumber</code>.
    * @alias module:model/RandomNumber
    * @class
    * @param rangeMin {Number} 
    * @param rangeMax {Number} 
    */

    constructor(rangeMin, rangeMax) {
        

        
        

        this['range_min'] = rangeMin;this['range_max'] = rangeMax;

        
    }

    /**
    * Constructs a <code>RandomNumber</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RandomNumber} obj Optional instance to populate.
    * @return {module:model/RandomNumber} The populated <code>RandomNumber</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RandomNumber();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [RandomNumberResult]);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], [DrawMetadata]);
            }
            if (data.hasOwnProperty('private_id')) {
                obj['private_id'] = ApiClient.convertToType(data['private_id'], 'String');
            }
            if (data.hasOwnProperty('range_min')) {
                obj['range_min'] = ApiClient.convertToType(data['range_min'], 'Number');
            }
            if (data.hasOwnProperty('range_max')) {
                obj['range_max'] = ApiClient.convertToType(data['range_max'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {Date} created_at
    */
    created_at = undefined;
    /**
    * @member {Date} updated_at
    */
    updated_at = undefined;
    /**
    * @member {String} title
    */
    title = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Array.<module:model/RandomNumberResult>} results
    */
    results = undefined;
    /**
    * @member {Array.<module:model/DrawMetadata>} metadata
    */
    metadata = undefined;
    /**
    * @member {String} private_id
    */
    private_id = undefined;
    /**
    * @member {Number} range_min
    */
    range_min = undefined;
    /**
    * @member {Number} range_max
    */
    range_max = undefined;








}


