# build environment
FROM node:lts
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm install --silent
COPY . /usr/src/app

ENV REACT_APP_ENV=production
RUN npm run build

ENV PORT 80
EXPOSE 80
CMD ["npm", "start"]
