# build environment
FROM node:dubnium

RUN mkdir /usr/src/app
RUN mkdir -p /var/log/eas3/

WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ENV LOGS_PATH /var/log/eas3

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm install --silent --production
COPY . /usr/src/app

ARG commit_sha=none
ENV REACT_APP_ENV=production
ENV REACT_APP_COMMIT=$commit_sha
RUN npm run build

ENV PORT 80
EXPOSE 80
CMD ["npm", "start"]
