# build environment
FROM node:dubnium

ARG commit_sha=none

RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm install --silent --production
COPY . /usr/src/app

ENV REACT_APP_ENV=production
ENV REACT_APP_COMMIT=$commit_sha
RUN npm run build

ENV PORT 80
EXPOSE 80
CMD ["npm", "start"]
