/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EchaloasuerteApi);
  }
}(this, function(expect, EchaloasuerteApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EchaloasuerteApi.DrawMetadata();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DrawMetadata', function() {
    it('should create an instance of DrawMetadata', function() {
      // uncomment below and update the code to test DrawMetadata
      //var instane = new EchaloasuerteApi.DrawMetadata();
      //expect(instance).to.be.a(EchaloasuerteApi.DrawMetadata);
    });

    it('should have the property client (base name: "client")', function() {
      // uncomment below and update the code to test the property client
      //var instane = new EchaloasuerteApi.DrawMetadata();
      //expect(instance).to.be();
    });

    it('should have the property key (base name: "key")', function() {
      // uncomment below and update the code to test the property key
      //var instane = new EchaloasuerteApi.DrawMetadata();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instane = new EchaloasuerteApi.DrawMetadata();
      //expect(instance).to.be();
    });

  });

}));
