/**
 * EAS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DrawMetadata from './model/DrawMetadata';
import DrawTossPayload from './model/DrawTossPayload';
import Participant from './model/Participant';
import Prize from './model/Prize';
import Raffle from './model/Raffle';
import RaffleResult from './model/RaffleResult';
import RaffleResultParticipant from './model/RaffleResultParticipant';
import RaffleResultPrize from './model/RaffleResultPrize';
import RaffleResultValue from './model/RaffleResultValue';
import RandomNumber from './model/RandomNumber';
import RandomNumberResult from './model/RandomNumberResult';
import RaffleApi from './api/RaffleApi';
import RandomNumberApi from './api/RandomNumberApi';


/**
* ERROR_UNKNOWN.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var EchaloasuerteApi = require('index'); // See note below*.
* var xxxSvc = new EchaloasuerteApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new EchaloasuerteApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new EchaloasuerteApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new EchaloasuerteApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DrawMetadata model constructor.
     * @property {module:model/DrawMetadata}
     */
    DrawMetadata,

    /**
     * The DrawTossPayload model constructor.
     * @property {module:model/DrawTossPayload}
     */
    DrawTossPayload,

    /**
     * The Participant model constructor.
     * @property {module:model/Participant}
     */
    Participant,

    /**
     * The Prize model constructor.
     * @property {module:model/Prize}
     */
    Prize,

    /**
     * The Raffle model constructor.
     * @property {module:model/Raffle}
     */
    Raffle,

    /**
     * The RaffleResult model constructor.
     * @property {module:model/RaffleResult}
     */
    RaffleResult,

    /**
     * The RaffleResultParticipant model constructor.
     * @property {module:model/RaffleResultParticipant}
     */
    RaffleResultParticipant,

    /**
     * The RaffleResultPrize model constructor.
     * @property {module:model/RaffleResultPrize}
     */
    RaffleResultPrize,

    /**
     * The RaffleResultValue model constructor.
     * @property {module:model/RaffleResultValue}
     */
    RaffleResultValue,

    /**
     * The RandomNumber model constructor.
     * @property {module:model/RandomNumber}
     */
    RandomNumber,

    /**
     * The RandomNumberResult model constructor.
     * @property {module:model/RandomNumberResult}
     */
    RandomNumberResult,

    /**
    * The RaffleApi service constructor.
    * @property {module:api/RaffleApi}
    */
    RaffleApi,

    /**
    * The RandomNumberApi service constructor.
    * @property {module:api/RandomNumberApi}
    */
    RandomNumberApi
};
