/**
 * EAS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DrawTossPayload from '../model/DrawTossPayload';
import RandomNumber from '../model/RandomNumber';
import RandomNumberResult from '../model/RandomNumberResult';

/**
 * RandomNumber service.
 * @module api/RandomNumberApi
 * @version v1
 */
export default class RandomNumberApi {
  /**
   * Constructs a new RandomNumberApi.
   * @alias module:api/RandomNumberApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * @param {module:model/RandomNumber} data
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RandomNumber} and HTTP response
   */
  randomNumberCreateWithHttpInfo(data) {
    const postBody = data;

    // verify the required parameter 'data' is set
    if (data === undefined || data === null) {
      throw new Error("Missing the required parameter 'data' when calling randomNumberCreate");
    }

    const pathParams = {};
    const queryParams = {};
    const headerParams = {};
    const formParams = {};

    const authNames = [];
    const contentTypes = ['application/json'];
    const accepts = ['application/json'];
    const returnType = RandomNumber;

    return this.apiClient.callApi(
      '/random_number/',
      'POST',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
    );
  }

  /**
   * @param {module:model/RandomNumber} data
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RandomNumber}
   */
  randomNumberCreate(data) {
    return this.randomNumberCreateWithHttpInfo(data).then(
      response_and_data => response_and_data.data,
    );
  }

  /**
   * @param {String} id
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RandomNumber} and HTTP response
   */
  randomNumberReadWithHttpInfo(id) {
    const postBody = null;

    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error("Missing the required parameter 'id' when calling randomNumberRead");
    }

    const pathParams = {
      id,
    };
    const queryParams = {};
    const headerParams = {};
    const formParams = {};

    const authNames = [];
    const contentTypes = ['application/json'];
    const accepts = ['application/json'];
    const returnType = RandomNumber;

    return this.apiClient.callApi(
      '/random_number/{id}/',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
    );
  }

  /**
   * @param {String} id
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RandomNumber}
   */
  randomNumberRead(id) {
    return this.randomNumberReadWithHttpInfo(id).then(response_and_data => response_and_data.data);
  }

  /**
   * @param {String} id
   * @param {module:model/DrawTossPayload} data
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RandomNumberResult} and HTTP response
   */
  randomNumberTossWithHttpInfo(id, data) {
    const postBody = data;

    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error("Missing the required parameter 'id' when calling randomNumberToss");
    }

    // verify the required parameter 'data' is set
    if (data === undefined || data === null) {
      throw new Error("Missing the required parameter 'data' when calling randomNumberToss");
    }

    const pathParams = {
      id,
    };
    const queryParams = {};
    const headerParams = {};
    const formParams = {};

    const authNames = [];
    const contentTypes = ['application/json'];
    const accepts = ['application/json'];
    const returnType = RandomNumberResult;

    return this.apiClient.callApi(
      '/random_number/{id}/toss/',
      'POST',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
    );
  }

  /**
   * @param {String} id
   * @param {module:model/DrawTossPayload} data
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RandomNumberResult}
   */
  randomNumberToss(id, data) {
    return this.randomNumberTossWithHttpInfo(id, data).then(
      response_and_data => response_and_data.data,
    );
  }
}
